### PR TITLE
add methods to change the output data rate

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e889408 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e889408f3ff3a83285deaa2366c5d3112c53f0e0 with merge 1eb0341c35cba4782869490e41c2fb573434b82c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/lsm303dlhc/builds/342867734?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 1eb0341c35cba4782869490e41c2fb573434b82c to master...

**Pull request merged**
