### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c54283a has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a80b2ed has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a80b2ed639c37ab19a21d5b3cef0c92ff12a0717 with merge 1ca17ab9f87e5712b1c2e895fe235637cb169f33...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/lsm303dlhc/builds/328487837?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 1ca17ab9f87e5712b1c2e895fe235637cb169f33 to master...

**Pull request merged**
