### PR TITLE
add `set_accel_sensitivity`

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c7f7c52 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c7f7c527e327dd311865b1d011acc0273235a6c7 with merge 6460dee6335fa2cdbfe40b490b1b33ea5ad6eceb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/lsm303dlhc/builds/328490156?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6460dee6335fa2cdbfe40b490b1b33ea5ad6eceb to master...

**Pull request merged**
